### ISSUE TITLE
New mirrors always appear as 'Down'

### ISSUE THREAD

**Issue by theodotos** [etix/mirrorbits#112]
We are experimenting with mirrorbits as a mirroring solution for Kali. But all the mirrors we add they always appear as 'Down'.

* Adding the mirror:

```
$ mirrorbits add -http http://archive-4.kali.org archive-4.kali.org -rsync rsync://archive-4.kali.org archive-4.kali.org
Mirror location:
Latitude:  48.8582
Longitude: 2.3387
Continent: EU
Country:   France
ASN:       OVH SAS (16276)

Mirror 'archive-4.kali.org' added successfully
Enable this mirror using
  $ mirrorbits enable archive-4.kali.org
```

* Enabling the mirror:

```
$ mirrorbits enable archive-4.kali.org
Mirror 'archive-4.kali.org' enabled successfully
```

* The mirror appears down with a very suspicious date:

```
$ mirrorbits list | grep archive-4.kali.org
archive-4.kali.org                      down    (Mon, 01 Jan 0001 00:00:00 UTC)
```

* I tried scanning:

```
$ mirrorbits scan archive-4.kali.org
Scanning archive-4.kali.org... done
```

* Same results:

```
$ mirrorbits list | grep archive-4.kali.org
archive-4.kali.org                      down    (Mon, 01 Jan 0001 00:00:00 UTC)
``` 

Note the redirection works just fine on the Fallback mirror.

This is our configuration in case it helps:

```
Repository: /srv/mirrors/kali

Templates: /home/archvsync/mirrorbits/templates

LogDir: /home/archvsync/log

GeoipDatabasePath: /home/archvsync/geoip/

OutputMode: redirect

Gzip: false

ListenAddress: :8080
RPCListenAddress: localhost:3390

RedisAddress: 127.0.0.1:6379
RedisDB: 0

TraceFileLocation: /project/trace/repo.kali.org

RepositoryScanInterval: 5

Hashes:
     SHA256: On
     SHA1: Off

ConcurrentSync: 5

ScanInterval: 30

CheckInterval: 1

Fallbacks:
     - URL: http://archive.kali.org/kali/
       CountryCode: ca
       ContinentCode: na
     - URL: http:/kali.download/kali/
       CountryCode: ca
       ContinentCode: na
```
